require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*
Layout/FirstParameterIndentation:
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Exclude:
    - spec/**/*
